packages:
  - "apps/web"    # Include the apps folder in the workspace
  - "apps/datajournalism.studio"    # Include the apps folder in the workspace
  - "packages/*" # Include any shared packages, if you have any
