// Capital city and (current, ~2024) population for every country in the world
// TopoJSON, keyed by its `properties.name`. Population figures are rounded recent
// estimates; capitals are the seats of government (constitutional capital where it
// differs from the largest city). `note` is an optional short context line.
export interface CountryFact {
  capital: string;
  population: string;
  note?: string;
}

export const FACTS: Record<string, CountryFact> = {
  Russia: { capital: "Moskva", population: "144 milionů", note: "Východní Evropa a severní Asie" },
  Antarctica: { capital: "—", population: "bez stálých obyvatel", note: "Kontinent bez státní správy" },
  Canada: { capital: "Ottawa", population: "41 milionů", note: "Severní Amerika; federace" },
  "United States of America": { capital: "Washington, D.C.", population: "341 milionů", note: "Severní Amerika; federální republika" },
  China: { capital: "Peking", population: "1,41 miliardy", note: "Východní Asie" },
  Brazil: { capital: "Brasília", population: "212 milionů", note: "Jižní Amerika; Mercosur je společný trh jihoamerických států" },
  Australia: { capital: "Canberra", population: "27 milionů", note: "Oceánie; stát i kontinent" },
  India: { capital: "Nové Dillí", population: "1,45 miliardy", note: "Jižní Asie; nejlidnatější země světa" },
  Argentina: { capital: "Buenos Aires", population: "46 milionů" },
  Kazakhstan: { capital: "Astana", population: "20 milionů" },
  "Dem. Rep. Congo": { capital: "Kinshasa", population: "105 milionů" },
  Algeria: { capital: "Alžír", population: "46 milionů", note: "Rozlohou největší země Afriky" },
  Greenland: { capital: "Nuuk", population: "57 tisíc", note: "Arktida; autonomní území Dánska" },
  Mexico: { capital: "Ciudad de México", population: "130 milionů" },
  "Saudi Arabia": { capital: "Rijád", population: "37 milionů" },
  Sudan: { capital: "Chartúm", population: "50 milionů" },
  Indonesia: { capital: "Jakarta", population: "281 milionů", note: "Největší souostrovní stát světa" },
  Libya: { capital: "Tripolis", population: "7,4 milionu" },
  Iran: { capital: "Teherán", population: "89 milionů" },
  Mongolia: { capital: "Ulánbátar", population: "3,5 milionu" },
  Peru: { capital: "Lima", population: "34 milionů" },
  Chad: { capital: "N'Djamena", population: "19 milionů" },
  Angola: { capital: "Luanda", population: "37 milionů" },
  Mali: { capital: "Bamako", population: "23 milionů" },
  "South Africa": { capital: "Pretoria", population: "63 milionů", note: "Jižní Afrika; Africká unie podporuje spolupráci afrických států" },
  Niger: { capital: "Niamey", population: "27 milionů" },
  Colombia: { capital: "Bogotá", population: "52 milionů" },
  Ethiopia: { capital: "Addis Abeba", population: "129 milionů" },
  Bolivia: { capital: "Sucre", population: "12 milionů" },
  Mauritania: { capital: "Nuakšott", population: "4,9 milionu" },
  Egypt: { capital: "Káhira", population: "114 milionů" },
  Tanzania: { capital: "Dodoma", population: "67 milionů" },
  Venezuela: { capital: "Caracas", population: "28 milionů" },
  Nigeria: { capital: "Abuja", population: "229 milionů", note: "Nejlidnatější země Afriky" },
  Pakistan: { capital: "Islámábád", population: "247 milionů" },
  Namibia: { capital: "Windhoek", population: "3 miliony" },
  Chile: { capital: "Santiago", population: "19,8 milionu" },
  Mozambique: { capital: "Maputo", population: "34 milionů" },
  Turkey: { capital: "Ankara", population: "85 milionů" },
  Zambia: { capital: "Lusaka", population: "21 milionů" },
  Myanmar: { capital: "Neipyijto", population: "54 milionů" },
  Afghanistan: { capital: "Kábul", population: "42 milionů" },
  France: { capital: "Paříž", population: "68 milionů", note: "Západní Evropa; EU je politické a hospodářské sdružení evropských států" },
  "S. Sudan": { capital: "Džuba", population: "11 milionů", note: "Nejmladší uznaný stát světa (2011)" },
  "Central African Rep.": { capital: "Bangui", population: "5,4 milionu" },
  Kenya: { capital: "Nairobi", population: "56 milionů" },
  Botswana: { capital: "Gaborone", population: "2,5 milionu" },
  Morocco: { capital: "Rabat", population: "37 milionů" },
  Madagascar: { capital: "Antananarivo", population: "30 milionů", note: "Indický oceán; ostrovní stát" },
  Ukraine: { capital: "Kyjev", population: "38 milionů", note: "Rozlohou největší celý stát v Evropě" },
  Thailand: { capital: "Bangkok", population: "72 milionů" },
  Spain: { capital: "Madrid", population: "48 milionů" },
  Somalia: { capital: "Mogadišo", population: "18 milionů" },
  Turkmenistan: { capital: "Ašchabad", population: "7,4 milionu" },
  "Papua New Guinea": { capital: "Port Moresby", population: "10 milionů" },
  Cameroon: { capital: "Yaoundé", population: "29 milionů" },
  Uzbekistan: { capital: "Taškent", population: "36 milionů" },
  Yemen: { capital: "Saná", population: "35 milionů" },
  Sweden: { capital: "Stockholm", population: "10,6 milionu" },
  Iraq: { capital: "Bagdád", population: "45 milionů" },
  Japan: { capital: "Tokio", population: "124 milionů", note: "Východní Asie; ostrovní stát" },
  Paraguay: { capital: "Asunción", population: "6,9 milionu" },
  Norway: { capital: "Oslo", population: "5,5 milionu" },
  Zimbabwe: { capital: "Harare", population: "16 milionů" },
  Germany: { capital: "Berlín", population: "84 milionů", note: "Střední Evropa; nejlidnatější stát EU" },
  Congo: { capital: "Brazzaville", population: "6,1 milionu" },
  Malaysia: { capital: "Kuala Lumpur", population: "34 milionů" },
  Finland: { capital: "Helsinky", population: "5,6 milionu" },
  Vietnam: { capital: "Hanoj", population: "100 milionů" },
  "Côte d'Ivoire": { capital: "Yamoussoukro", population: "29 milionů" },
  Italy: { capital: "Řím", population: "59 milionů" },
  Oman: { capital: "Maskat", population: "5,2 milionu" },
  Poland: { capital: "Varšava", population: "37 milionů" },
  Philippines: { capital: "Manila", population: "116 milionů" },
  "New Zealand": { capital: "Wellington", population: "5,3 milionu" },
  "Burkina Faso": { capital: "Ouagadougou", population: "23 milionů" },
  Gabon: { capital: "Libreville", population: "2,4 milionu" },
  Ecuador: { capital: "Quito", population: "18 milionů" },
  "United Kingdom": { capital: "Londýn", population: "69 milionů" },
  Uganda: { capital: "Kampala", population: "49 milionů" },
  Ghana: { capital: "Akkra", population: "34 milionů" },
  Guinea: { capital: "Conakry", population: "14 milionů" },
  Romania: { capital: "Bukurešť", population: "19 milionů" },
  Laos: { capital: "Vientiane", population: "7,7 milionu" },
  Guyana: { capital: "Georgetown", population: "0,8 milionu" },
  Belarus: { capital: "Minsk", population: "9,1 milionu" },
  Kyrgyzstan: { capital: "Biškek", population: "7,1 milionu" },
  Senegal: { capital: "Dakar", population: "18 milionů" },
  Syria: { capital: "Damašek", population: "24 milionů" },
  Cambodia: { capital: "Phnompenh", population: "17 milionů" },
  Uruguay: { capital: "Montevideo", population: "3,4 milionu" },
  Somaliland: { capital: "Hargeisa", population: "5,7 milionu", note: "Samostatně vyhlášený stát, mezinárodně neuznaný" },
  Tunisia: { capital: "Tunis", population: "12 milionů" },
  Nepal: { capital: "Káthmándú", population: "30 milionů" },
  Suriname: { capital: "Paramaribo", population: "0,6 milionu" },
  Tajikistan: { capital: "Dušanbe", population: "10 milionů" },
  Bangladesh: { capital: "Dháka", population: "173 milionů" },
  Greece: { capital: "Athény", population: "10,4 milionu" },
  Nicaragua: { capital: "Managua", population: "7 milionů" },
  "North Korea": { capital: "Pchjongjang", population: "26 milionů" },
  Eritrea: { capital: "Asmara", population: "3,7 milionu" },
  Benin: { capital: "Porto-Novo", population: "14 milionů" },
  Cuba: { capital: "Havana", population: "11 milionů" },
  Honduras: { capital: "Tegucigalpa", population: "11 milionů" },
  Malawi: { capital: "Lilongwe", population: "21 milionů" },
  Bulgaria: { capital: "Sofie", population: "6,4 milionu" },
  Guatemala: { capital: "Guatemala", population: "18 milionů" },
  Iceland: { capital: "Reykjavík", population: "0,39 milionu", note: "Nejřidčeji osídlená země Evropy" },
  "South Korea": { capital: "Soul", population: "52 milionů" },
  Liberia: { capital: "Monrovia", population: "5,6 milionu" },
  "W. Sahara": { capital: "El Aaiún", population: "0,6 milionu", note: "Sporné území; z většiny spravováno Marokem" },
  Portugal: { capital: "Lisabon", population: "10,6 milionu" },
  Hungary: { capital: "Budapešť", population: "9,6 milionu" },
  Azerbaijan: { capital: "Baku", population: "10 milionů" },
  Jordan: { capital: "Ammán", population: "11 milionů" },
  Austria: { capital: "Vídeň", population: "9,2 milionu", note: "Střední Evropa; EU je politické a hospodářské sdružení evropských států" },
  Czechia: { capital: "Praha", population: "10,9 milionu", note: "Střední Evropa; EU je politické a hospodářské sdružení evropských států" },
  "United Arab Emirates": { capital: "Abú Zabí", population: "10 milionů" },
  "Sierra Leone": { capital: "Freetown", population: "8,6 milionu" },
  Serbia: { capital: "Bělehrad", population: "6,6 milionu" },
  Panama: { capital: "Panama", population: "4,5 milionu" },
  Georgia: { capital: "Tbilisi", population: "3,7 milionu" },
  "Sri Lanka": { capital: "Kolombo", population: "22 milionů" },
  Latvia: { capital: "Riga", population: "1,9 milionu" },
  Lithuania: { capital: "Vilnius", population: "2,9 milionu" },
  Togo: { capital: "Lomé", population: "9,1 milionu", note: "Předkladatel rezoluce OSN „Correct the Map“" },
  Ireland: { capital: "Dublin", population: "5,3 milionu" },
  Croatia: { capital: "Záhřeb", population: "3,9 milionu" },
  "Costa Rica": { capital: "San José", population: "5,2 milionu" },
  "Bosnia and Herz.": { capital: "Sarajevo", population: "3,2 milionu" },
  "Dominican Rep.": { capital: "Santo Domingo", population: "11 milionů" },
  Slovakia: { capital: "Bratislava", population: "5,4 milionu", note: "Střední Evropa; EU je politické a hospodářské sdružení evropských států" },
  Switzerland: { capital: "Bern", population: "8,9 milionu" },
  Estonia: { capital: "Tallinn", population: "1,4 milionu" },
  Denmark: { capital: "Kodaň", population: "5,9 milionu" },
  Netherlands: { capital: "Amsterodam", population: "18 milionů" },
  Bhutan: { capital: "Thimphú", population: "0,79 milionu" },
  "Guinea-Bissau": { capital: "Bissau", population: "2,2 milionu" },
  Taiwan: { capital: "Tchaj-pej", population: "23 milionů" },
  Moldova: { capital: "Kišiněv", population: "2,4 milionu" },
  Belgium: { capital: "Brusel", population: "11,8 milionu", note: "Sídlo hlavních institucí EU a NATO" },
  Albania: { capital: "Tirana", population: "2,7 milionu" },
  Haiti: { capital: "Port-au-Prince", population: "11,7 milionu" },
  Armenia: { capital: "Jerevan", population: "3 miliony" },
  Lesotho: { capital: "Maseru", population: "2,3 milionu", note: "Enkláva zcela obklopená Jihoafrickou republikou" },
  "Eq. Guinea": { capital: "Malabo", population: "1,7 milionu" },
  Burundi: { capital: "Gitega", population: "13 milionů" },
  Macedonia: { capital: "Skopje", population: "1,8 milionu", note: "Oficiálně Severní Makedonie" },
  "Solomon Is.": { capital: "Honiara", population: "0,74 milionu" },
  Rwanda: { capital: "Kigali", population: "14 milionů" },
  "New Caledonia": { capital: "Nouméa", population: "0,27 milionu", note: "Zámořské území Francie" },
  Israel: { capital: "Jeruzalém", population: "9,8 milionu" },
  Belize: { capital: "Belmopan", population: "0,41 milionu" },
  Djibouti: { capital: "Džibuti", population: "1,1 milionu" },
  "El Salvador": { capital: "San Salvador", population: "6,3 milionu" },
  Fiji: { capital: "Suva", population: "0,93 milionu" },
  Slovenia: { capital: "Lublaň", population: "2,1 milionu" },
  eSwatini: { capital: "Mbabane", population: "1,2 milionu", note: "Dříve Svazijsko" },
  Kuwait: { capital: "Kuvajt", population: "4,9 milionu" },
  "Falkland Is.": { capital: "Stanley", population: "3,7 tisíce", note: "Zámořské území Spojeného království" },
  Bahamas: { capital: "Nassau", population: "0,41 milionu" },
  "Timor-Leste": { capital: "Dili", population: "1,4 milionu" },
  Gambia: { capital: "Banjul", population: "2,8 milionu" },
  Montenegro: { capital: "Podgorica", population: "0,62 milionu" },
  Jamaica: { capital: "Kingston", population: "2,8 milionu" },
  "Fr. S. Antarctic Lands": { capital: "Port-aux-Français", population: "bez stálých obyvatel", note: "Francouzská jižní a antarktická území" },
  Qatar: { capital: "Dauhá", population: "3 miliony" },
  Kosovo: { capital: "Priština", population: "1,6 milionu", note: "Nezávislost vyhlásilo v roce 2008" },
  Brunei: { capital: "Bandar Seri Begawan", population: "0,46 milionu" },
  Lebanon: { capital: "Bejrút", population: "5,4 milionu" },
  "Puerto Rico": { capital: "San Juan", population: "3,2 milionu", note: "Nezačleněné území USA" },
  "Trinidad and Tobago": { capital: "Port of Spain", population: "1,4 milionu" },
  Vanuatu: { capital: "Port Vila", population: "0,33 milionu" },
  Cyprus: { capital: "Nikósie", population: "1,3 milionu" },
  Palestine: { capital: "Ramalláh", population: "5,4 milionu", note: "Sídlo správy; nárokovaným hlavním městem je Východní Jeruzalém" },
  "N. Cyprus": { capital: "Severní Nikósie", population: "0,38 milionu", note: "Uznávané pouze Tureckem" },
  Luxembourg: { capital: "Lucemburk", population: "0,67 milionu", note: "Sídlo části institucí EU" },
};
