'use client';

import {
  Anchor,
  Badge,
  Box,
  Group,
  SimpleGrid,
  Stack,
  Text,
  Title,
  useMantineTheme,
} from '@mantine/core';
import type { MantineSize } from '@mantine/core';
import { Fragment, useEffect, useRef, useState } from 'react';
import type { Article } from '../lib/getArticles';
import { fixCzechTypography } from '../lib/remark-czech-typography';
import { fitFor, resolvePaletteColor } from '../lib/coverFit';
import styles from './box.module.css';

// Mirrors apps/web/utils/authorUtils.ts so the author-page slugs produced here
// match those generated by /autor/[slug] generateStaticParams. Keep in sync.
function normalizeAuthor(author: string): string {
  return author
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function splitAuthors(author: string | undefined): string[] {
  if (!author) return [];
  return author
    .split(/,|&|\s+and\s+|\s+a\s+/i)
    .map((a) => a.trim())
    .filter(Boolean);
}

type Preset = 'sidebar' | 'cards' | 'list';
type ImagePos = 'top' | 'left' | 'right' | 'none';
type CardBg = 'white' | 'cream' | 'transparent';
type SortOrder = 'default' | 'newest';
type FloatPos = 'right' | 'left' | 'none';

interface RelatedArticlesProps {
  // Data (injected from scope by ArticleRenderer)
  pool?: Article[];

  // Optional floating layout (similar to InfoBox)
  float?: FloatPos;
  position?: FloatPos;

  // Filtering (set by author in MDX)
  filter?: string | string[];
  tag?: string;
  slugs?: string[];   // hard-coded list; overrides filter/tag when provided
  count?: number;

  // Heading – pass false to suppress the heading and its border entirely
  heading?: string | false;

  // Sort order
  sort?: SortOrder;

  // Preset
  preset?: Preset;

  // Layout overrides
  columns?: 1 | 2 | 3 | 4;
  imagePosition?: ImagePos;
  cardBackground?: CardBg;
  titleSize?: MantineSize;

  // Show/hide toggles
  showExcerpt?: boolean;
  showImage?: boolean;
  showDate?: boolean;
  showReadingTime?: boolean;
  showAuthor?: boolean;
  showFormatBadge?: boolean;
  showEmbed?: boolean;
  showTopicBadge?: boolean;

  // App-specific
  articleBasePath?: string;
  authorBasePath?: string;
  locale?: string;
}

interface PresetConfig {
  columns: 1 | 2 | 3 | 4;
  imagePosition: ImagePos;
  cardBackground: CardBg;
  titleSize: MantineSize;
  showAuthor: boolean;
  showExcerpt: boolean;
  showDate: boolean;
  showReadingTime: boolean;
  showFormatBadge: boolean;
  showTopicBadge: boolean;
  showEmbed: boolean;
  showImage: boolean;
}

const PRESET_DEFAULTS: Record<Preset, PresetConfig> = {
  sidebar: {
    columns: 1,
    imagePosition: 'left',
    cardBackground: 'cream',
    titleSize: 'sm',
    showAuthor: false,
    showExcerpt: false,
    showDate: true,
    showReadingTime: false,
    showFormatBadge: true,
    showTopicBadge: false,
    showEmbed: false,
    showImage: true,
  },
  cards: {
    columns: 3,
    imagePosition: 'top',
    cardBackground: 'white',
    titleSize: 'md',
    showAuthor: false,
    showExcerpt: true,
    showDate: true,
    showReadingTime: false,
    showFormatBadge: true,
    showTopicBadge: false,
    showEmbed: false,
    showImage: true,
  },
  list: {
    columns: 1,
    imagePosition: 'left',
    cardBackground: 'white',
    titleSize: 'lg',
    showAuthor: true,
    showExcerpt: true,
    showDate: true,
    showReadingTime: true,
    showFormatBadge: true,
    showTopicBadge: true,
    showEmbed: false,
    showImage: true,
  },
};

function getFilterLabel(filter: string | string[] | undefined): string | null {
  if (!filter) return null;
  const first = Array.isArray(filter) ? filter[0] : filter;
  if (!first) return null;
  return first.charAt(0).toUpperCase() + first.slice(1);
}

function useFilterColor(filter: string | string[] | undefined): string {
  const theme = useMantineTheme();
  const first = Array.isArray(filter) ? filter[0] : filter;
  const val = (first ?? '').toLowerCase();

  const map: Record<string, string> = {
    analýza: theme.colors.brand[6],
    analyza: theme.colors.brand[6],
    kontext: theme.colors.brandNavy[6],
    komentář: theme.colors.brandOrange[6],
    komentar: theme.colors.brandOrange[6],
    komentare: theme.colors.brandOrange[6],
    podcast: theme.colors.brandTeal[6],
    data: theme.colors.brandTeal[6],
  };

  return map[val] ?? theme.colors.brand[6];
}

function cardBgValue(bg: CardBg): string {
  // Cards sit as the lighter layer on top of the section frame: pure white for
  // the text/excerpt area under the cover image, cream one step down for the
  // 'cream' variant. See packages/ui/DESIGN.md → RelatedArticles.
  if (bg === 'white') return 'background.0';
  if (bg === 'cream') return 'background.1';
  return 'transparent';
}

interface MiniCardProps {
  article: Article;
  imagePosition: ImagePos;
  cardBackground: CardBg;
  titleSize: MantineSize;
  showExcerpt: boolean;
  showImage: boolean;
  showDate: boolean;
  showReadingTime: boolean;
  showAuthor: boolean;
  showFormatBadge: boolean;
  showEmbed: boolean;
  showTopicBadge: boolean;
  articleBasePath: string;
  authorBasePath?: string;
  locale: string;
}

function MiniCard({
  article,
  imagePosition,
  cardBackground,
  titleSize,
  showExcerpt,
  showImage,
  showDate,
  showReadingTime,
  showAuthor,
  showFormatBadge,
  showEmbed,
  showTopicBadge,
  articleBasePath,
  authorBasePath,
  locale,
}: MiniCardProps) {
  const theme = useMantineTheme();
  const href = article.href || `${articleBasePath}/${article.slug}`;
  const bg = cardBgValue(cardBackground);
  const filterColor = useFilterColor(article.filter);
  const filterLabel = getFilterLabel(article.filter);

  // Náhled 5:4 se chová stejně jako na homepage (ArticleCard): u 'auto' se podle
  // skutečného poměru obrázku rozhodne mezi ořezem (cover) a celým obrázkem +
  // pruhem barvy (contain), ať se z náhledu neztratí text/důležitá část.
  const coverBgColor = resolvePaletteColor(theme, article.coverBg, '#ffffff');
  const [autoFit, setAutoFit] = useState<'cover' | 'contain'>('cover');
  const imgRef = useRef<HTMLImageElement | null>(null);
  const coverFit = article.coverFit ?? 'auto';
  const fit: 'cover' | 'contain' =
    coverFit === 'cover' || coverFit === 'contain' ? coverFit : autoFit;
  useEffect(() => {
    if (coverFit !== 'auto') return;
    const el = imgRef.current;
    if (el && el.naturalWidth && el.naturalHeight) {
      setAutoFit(fitFor(el.naturalWidth, el.naturalHeight));
    }
  }, [article.coverImage, coverFit]);

  const hasImage = showImage && article.coverImage;

  // Rubric badge (ANALÝZA/KONTEXT…) – an oval that sits in the top-right corner
  // of the cover thumbnail, exactly like the homepage ArticleCard. When the card
  // has no image, it falls back into the text block instead.
  const formatBadge =
    showFormatBadge && filterLabel ? (
      <Badge
        size="xs"
        className={styles.relatedBadge}
        style={{ backgroundColor: filterColor, color: '#fff' }}
      >
        {filterLabel}
      </Badge>
    ) : null;

  const topicBadge =
    showTopicBadge && article.topic ? (
      <Badge size="xs" variant="outline" color="brandNavy.6" className={styles.relatedBadge}>
        {article.topic}
      </Badge>
    ) : null;

  // Same rubric badge, but positioned in the top-right corner of the cover
  // (like the homepage ArticleCard). Applied directly to the Badge — no wrapper —
  // so the offsets match `.rating` exactly.
  const overlayBadge =
    showFormatBadge && filterLabel ? (
      <Badge
        size="xs"
        className={`${styles.relatedBadge} ${styles.relatedBadgeOverlay}`}
        style={{ backgroundColor: filterColor, color: '#fff' }}
      >
        {filterLabel}
      </Badge>
    ) : null;

  // In-text badges: topic always; the rubric badge only as a fallback when there
  // is no cover image to overlay it on.
  const textBadges = (topicBadge || (!hasImage && formatBadge)) && (
    <Group gap={4} wrap="wrap">
      {!hasImage && formatBadge}
      {topicBadge}
    </Group>
  );

  const dateText = (showDate || showReadingTime) && (
    <Text size="xs" mt={4} c="brandNavy.9">
      {showDate && new Date(article.date).toLocaleDateString(locale)}
      {showDate && showReadingTime && article.readingTime ? ' · ' : ''}
      {showReadingTime && article.readingTime ? `${article.readingTime} min` : ''}
    </Text>
  );

  const titleEl = (
    <Anchor
      href={href}
      underline="hover"
      c="inherit"
      target="_blank"
      rel="noopener noreferrer"
      className={styles.relatedCardLink}
    >
      <Text fw={600} size={titleSize} lh={1.3}>
        {fixCzechTypography(article.title)}
      </Text>
    </Anchor>
  );

  const excerpt = showExcerpt && article.excerpt && (
    <Text size="sm" c="brandNavy.9" lineClamp={3}>
      {fixCzechTypography(article.excerpt)}
    </Text>
  );

  const authorNames = splitAuthors(article.author);
  const authorText = showAuthor && authorNames.length > 0 && (
    <Text size="xs" mt={6} c={theme.black} fw={400}>
      {authorNames.map((name, i) => (
        <Fragment key={name}>
          {authorBasePath ? (
            <Anchor
              href={`${authorBasePath}/${normalizeAuthor(name)}`}
              c="inherit"
              fw={400}
              underline="hover"
              className={styles.relatedAuthorLink}
            >
              {name}
            </Anchor>
          ) : (
            name
          )}
          {i < authorNames.length - 1 ? ' & ' : ''}
        </Fragment>
      ))}
    </Text>
  );

  const embed = showEmbed && article.embedHtml && (
    <Box dangerouslySetInnerHTML={{ __html: article.embedHtml }} />
  );

  const textBlock = (
    <Stack gap={4} style={{ flex: 1 }}>
      {textBadges}
      {titleEl}
      {excerpt}
      {dateText}
      {authorText}
      {embed}
    </Stack>
  );

  if (!hasImage || imagePosition === 'none') {
    return (
      <Box
        className={styles.relatedCard}
        bg={bg}
        p={cardBackground !== 'transparent' ? 'sm' : 0}
        style={{ borderRadius: 6 }}
      >
        {textBlock}
      </Box>
    );
  }

  if (imagePosition === 'top') {
    return (
      <Box className={styles.relatedCard} bg={bg} style={{ borderRadius: 6, overflow: 'hidden' }}>
        <Box
          style={{
            position: 'relative',
            aspectRatio: '5 / 4',
            overflow: 'hidden',
            background: fit === 'contain' ? coverBgColor : undefined,
          }}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            ref={imgRef}
            src={article.coverImage!}
            alt={article.title}
            loading="lazy"
            onLoad={(e) => {
              if (coverFit === 'auto') {
                const el = e.currentTarget;
                setAutoFit(fitFor(el.naturalWidth, el.naturalHeight));
              }
            }}
            style={{ objectFit: fit, display: 'block', width: '100%', height: '100%' }}
          />
          {overlayBadge}
        </Box>
        <Box p="sm">
          {textBlock}
        </Box>
      </Box>
    );
  }

  // left or right – fixed-width 5:4 container keeps thumbnails uniform. The cover
  // uses the same fit logic as the homepage (contain + colour band instead of a
  // crop that would cut text out of the image).
  const imgEl = (
    <Box
      style={{
        position: 'relative',
        flexShrink: 0,
        width: 120,
        aspectRatio: '5 / 4',
        overflow: 'hidden',
        borderRadius: 4,
        background: fit === 'contain' ? coverBgColor : undefined,
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        ref={imgRef}
        src={article.coverImage!}
        alt={article.title}
        loading="lazy"
        onLoad={(e) => {
          if (coverFit === 'auto') {
            const el = e.currentTarget;
            setAutoFit(fitFor(el.naturalWidth, el.naturalHeight));
          }
        }}
        style={{ objectFit: fit, width: '100%', height: '100%', display: 'block' }}
      />
      {overlayBadge}
    </Box>
  );

  return (
    <Box
      className={styles.relatedCard}
      bg={bg}
      p={cardBackground !== 'transparent' ? 'sm' : 0}
      style={{ borderRadius: 6 }}
    >
      <Group gap="sm" align="flex-start" wrap="nowrap">
        {imagePosition === 'left' && imgEl}
        {textBlock}
        {imagePosition === 'right' && imgEl}
      </Group>
    </Box>
  );
}

export function RelatedArticles({
  pool = [],
  float,
  position,
  filter,
  tag,
  slugs,
  count = 4,
  heading,
  sort = 'default',
  preset = 'cards',
  columns,
  imagePosition,
  cardBackground,
  titleSize,
  showExcerpt,
  showImage,
  showDate,
  showReadingTime,
  showAuthor,
  showFormatBadge,
  showEmbed,
  showTopicBadge,
  articleBasePath = '/clanek',
  authorBasePath,
  locale = 'cs-CZ',
}: RelatedArticlesProps) {
  const defaults = PRESET_DEFAULTS[preset];

  const floatPos: FloatPos | undefined = float ?? position;
  const floatClass =
    floatPos === 'right' ? styles.floatRight :
    floatPos === 'left' ? styles.floatLeft :
    undefined;

  // Explicit props override preset defaults
  const effectiveColumns    = columns        ?? defaults.columns;
  const effectiveImgPos     = imagePosition  ?? defaults.imagePosition;
  // Floating side box is framed like the 'cards' block (cream container), so
  // its cards turn white to stand out from the frame.
  const effectiveBg         = cardBackground ?? (floatClass ? 'white' : defaults.cardBackground);
  const effectiveTitleSize  = titleSize      ?? defaults.titleSize;
  const effectiveShowExcerpt      = showExcerpt      ?? defaults.showExcerpt;
  const effectiveShowImage        = showImage        ?? defaults.showImage;
  const effectiveShowDate         = showDate         ?? defaults.showDate;
  const effectiveShowReadingTime  = showReadingTime  ?? defaults.showReadingTime;
  const effectiveShowAuthor       = showAuthor       ?? defaults.showAuthor;
  const effectiveShowFormatBadge  = showFormatBadge  ?? defaults.showFormatBadge;
  const effectiveShowEmbed        = showEmbed        ?? defaults.showEmbed;
  const effectiveShowTopicBadge   = showTopicBadge   ?? defaults.showTopicBadge;

  const defaultHeading = locale.startsWith('cs') ? '🔻🔻🔻' : 'Recommended';
  const effectiveHeading = heading === false ? null : (heading ?? defaultHeading);

  // Build display list
  let items: Article[];
  if (slugs && slugs.length > 0) {
    // Hard-coded list: preserve author-specified order, look up from pool
    const bySlug = new Map(pool.map(a => [a.slug, a]));
    items = slugs.flatMap(s => { const a = bySlug.get(s); return a ? [a] : []; });
  } else {
    // Filter pool (already sorted by score)
    items = pool;
    if (filter) {
      const f = Array.isArray(filter) ? filter : [filter];
      items = items.filter(a => {
        const af = Array.isArray(a.filter) ? a.filter : [a.filter ?? ''];
        return f.some(v => af.includes(v));
      });
    }
    if (tag) {
      items = items.filter(a => a.tags?.includes(tag));
    }
    if (sort === 'newest') {
      items = [...items].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    }
  }
  const displayed = items.slice(0, count);

  if (displayed.length === 0) return null;

  // 'cards' and the floating side box ("Napsali jsme") render as a framed
  // section: a cream (#f8f6f0) container that underlays the lighter (white)
  // cards. Other presets stay frameless.
  const framed = preset === 'cards' || !!floatClass;

  return (
    <Box
      // Floating variant takes its margins from the shared bleed standard
      // (box.module.css); Mantine's inline `my` would override them.
      my={floatClass ? undefined : 'xl'}
      className={floatClass}
      bg={framed ? 'background.2' : undefined}
      p={framed ? (floatClass ? 'md' : 'lg') : undefined}
      style={framed ? { borderRadius: 10 } : undefined}
    >
      {effectiveHeading && (
        <Title order={3} c="brand.6" mb="xs">
          {effectiveHeading}
        </Title>
      )}
      <SimpleGrid cols={{ base: 1, sm: effectiveColumns }}>
        {displayed.map(article => (
          <MiniCard
            key={article.slug}
            article={article}
            imagePosition={effectiveImgPos}
            cardBackground={effectiveBg}
            titleSize={effectiveTitleSize}
            showExcerpt={effectiveShowExcerpt}
            showImage={effectiveShowImage}
            showDate={effectiveShowDate}
            showReadingTime={effectiveShowReadingTime}
            showAuthor={effectiveShowAuthor}
            showFormatBadge={effectiveShowFormatBadge}
            showEmbed={effectiveShowEmbed}
            showTopicBadge={effectiveShowTopicBadge}
            articleBasePath={articleBasePath}
            authorBasePath={authorBasePath}
            locale={locale}
          />
        ))}
      </SimpleGrid>
    </Box>
  );
}

export default RelatedArticles;
